controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

diff_cont:
  type: diff_drive_controller/DiffDriveController
  ros__parameters:
    publish_rate: 30.0
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.16
    wheel_radius: 0.0375
    use_stamped_vel: false

joint_broad:
  type: joint_state_broadcaster/JointStateBroadcaster
  ros__parameters: {}
